### ISSUE TITLE
is it still maintaining?

### ISSUE THREAD

**Issue by phatify** [caloudinou/jsend-format-response#8]
A very cool module. Is it still maintaining at current?

**Comment by caloudinou** [comment]
Yes, it's maintained. I' will make a new version this next weekend

**Comment by phatify** [comment]
> Yes, it's maintained. I' will make a new version this next weekend

thank you so much.  I appreciate it!

**Comment by phatify** [comment]
@caloudinou  I'm looking forward to you apply `Builder design pattern` as `chainable methods` to refactor this.
Example: 

Success:

      res.success(200).data('some data').payload('some payload').message('successfully!');

Failure:

      res.fail(404).message('Not found resource').errors([{ key: 'type of error', value: 'describe of error' }]);

Error:

      res.error(500).message('Something went wrong!');

Hope you implement it!
